In [1]:
type(1.0)


float

In [2]:
int(True)

1

In [3]:
1/2

0.5

In [4]:
r=1/1
type(r)

float

In [5]:
print("AB\nC\nDE")

AB
C
DE


In [6]:
print("AB\nC\nDE")

AB
C
DE


In [7]:
"hello Mike".find("Mike")

6

In [8]:
name = 'Lizz'

In [9]:
print(name[0:2])

Li


In [10]:
A='1934567'

In [11]:
A[1::2]

'946'

In [12]:
'1'+'2'

'12'

In [13]:
myvar = 'hello'

In [14]:
myvar.upper()

'HELLO'

In [15]:
Name="ABCDE"

In [16]:
Name.find("B")

1

In [17]:
str(1+1)

'2'

In [18]:
"123".replace("12", "ab")

'ab3'

In [19]:
say_what=('say',' what', 'you', 'will')

In [20]:
say_what[-1]

'will'

In [21]:
A=(1,2,3,4,5)

In [22]:
A[1:4]

(2, 3, 4)

In [23]:
B=[1,2,[3,'a'],[4,'b']]

In [24]:
B[3][1]

'b'

In [25]:
[1,2,3]+[1,1,1]

[1, 2, 3, 1, 1, 1]

In [26]:
"Hello Mike".split()

['Hello', 'Mike']

In [27]:
tuple1=("A","B","C" )

In [28]:
tuple1[-1]

'C'

In [29]:
A=((11,12),[21,22])

In [30]:
 A[1]

[21, 22]

In [31]:
A=((1),[2,3],[4])

In [32]:
A[2][0]

4

In [33]:
'A,B,C,D'.split(',')

['A', 'B', 'C', 'D']

In [34]:
A=["hard rock",10,1.2]

In [35]:
del(A[0])

In [36]:
A

[10, 1.2]

In [37]:
B=A

In [38]:
B

[10, 1.2]

In [39]:
len(("disco",10))

2

In [40]:
Dict={"A":1,"B":"2","C":[3,3,3],"D":(4,4,4),'E':5,'F':6}

In [41]:
Dict["D"]

(4, 4, 4)

In [42]:
{ "The Bodyguard":"1992", "Saturday Night Fever":"1977"}

{'The Bodyguard': '1992', 'Saturday Night Fever': '1977'}

In [43]:
release_year_dict.keys()

NameError: name 'release_year_dict' is not defined

In [44]:
 {'a':1, 'a':2}

{'a': 2}

In [45]:
set(a)

NameError: name 'a' is not defined

In [46]:
V={'A','B'}

In [47]:
V.add('C')

In [48]:
V

{'A', 'B', 'C'}

In [49]:
'A' in {'A','B'}

True

In [50]:
1=2

SyntaxError: can't assign to literal (<ipython-input-50-a0aef98f5518>, line 1)

In [51]:
i=6
i<5

False

In [52]:
5!=5

False

In [53]:
'a'=='A'

False

In [54]:
x="Go"

if(x=="Go"):

  print('Go ')

else:

  print('Stop')

print('Mike')

Go 
Mike


In [55]:
x=1
x>5

False

In [56]:
x=1

if(x!=1):

  print('Hello')

else:

  print('Hi')

print('Mike')

Hi
Mike


In [57]:
A=[1,2,3]

for a in A:

  print(2*a)

2
4
6


In [58]:
x=5
while(x!=2):
  print(x)
  x=x-1

5
4
3


In [59]:
for i,x in enumerate(['A','B','C']):
    print(i+1,x)

1 A
2 B
3 C


In [60]:
for i in range(1,5):
    if (i==2):
        print(i)

2


In [61]:
def add(x):
    return(x+x)
    
add('1')

'11'

In [62]:
def hello():
    print("hello")

In [63]:
a=1

def do(x):
    a=100
    return(x+a)

print(do(1))

101


In [64]:
RedCircle=Circle(10,'red')
RedCircle.radius=1

NameError: name 'Circle' is not defined

In [65]:
class Point(object):

  def __init__(self,x,y):

    self.x=x
    self.y=y

  def print_point(self):

    print('x=',self.x,'y=',self.y)


In [66]:
class Points(object):
  def __init__(self,x,y):

    self.x=x
    self.y=y

  def print_point(self):

    print('x=',self.x,' y=',self.y)

p1=Points("A","B")
p1.print_point()

x= A  y= B


In [67]:
class Points(object):

  def __init__(self,x,y):

    self.x=x
    self.y=y

  def print_point(self):

    print('x=',self.x,' y=',self.y)

p2=Points(1,2)

p2.x='A'

p2.print_point()

x= A  y= 2


In [68]:
a=np.array([0,1,0,1,0])
b=np.array([1,0,1,0,1])
a*b

NameError: name 'np' is not defined

In [69]:
import numpy as np
a=np.array([0,1,0,1,0])
b=np.array([1,0,1,0,1])
a*b

array([0, 0, 0, 0, 0])

In [70]:
a=np.array([-1,1])
b=np.array([1,1])
np.dot(a,b) 

0

In [71]:
a=np.array([1,1,1,1,1])
a+10 

array([11, 11, 11, 11, 11])

In [1]:
A=np.array([[1,0,1],[2,2,2]])

NameError: name 'np' is not defined

In [2]:
import numpy as np
A=np.array([[1,0,1],[2,2,2]])

In [3]:
A[0,1]

0

In [4]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0:2,2]
out

array([1, 2])

In [5]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]]) 
Z=np.dot(X,Y)

In [6]:
Z

array([[2, 1],
       [1, 2]])

In [1]:
df1=pd.DataFrame({'A':["a","b","a","c","a","c","b"]})
df1['A'].value_counts()

NameError: name 'pd' is not defined

In [2]:
import pandas as pd
df1=pd.DataFrame({'A':["a","b","a","c","a","c","b"]})
df1['A'].value_counts()

a    3
c    2
b    2
Name: A, dtype: int64

In [3]:
x=df[“engine-size”]
y=df[“price”]
plt.scatter(x,y)
plt.title(“Scatterplot of Engine Size vs Price”)
plt.xlabel(“Engine Size”) 
plt.ylabel(“Price”) 



SyntaxError: invalid character in identifier (<ipython-input-3-c28c69da4516>, line 1)

In [5]:
x=df["engine-size"]
y=df["price"]
plt.scatter(x,y)
plt.title("Scatterplot of Engine Size vs Price")
plt.xlabel("Engine Size") 
plt.ylabel("Price") 


NameError: name 'df' is not defined

In [6]:
from sklearn.linear_model import LinearRegression 
lm=LinearRegression()
X = df[['highway-mpg']]
Y = df['price']
lm.fit(X, Y)
Yhat=lm.predict(X)

NameError: name 'df' is not defined